### Zomato sales analyse

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
sales_data = np.array([
    [1, 1200, 1350, 1500, 1600],
    [2, 1100, 1250, 1400, 1550],
    [3, 1300, 1450, 1550, 1700],
    [4, 1000, 1150, 1300, 1400],
    [5, 1250, 1400, 1500, 1650]
])

print("=== Zomato data sales analysis ===")

print(f"Shape : {np.shape(sales_data)}")

=== Zomato data sales analysis ===
Shape : (5, 5)


In [12]:
# Data for first 3 restaurants 
print(f"Data for first 3 restaurants : \n{sales_data[:3]}")

Data for first 3 restaurants : 
[[   1 1200 1350 1500 1600]
 [   2 1100 1250 1400 1550]
 [   3 1300 1450 1550 1700]]


In [19]:
# Total sales per year
print(f"Year wise sales per restaurants : {np.sum(sales_data[:,1:], axis=0)}")  # all rows, excluded rest_id

Year wise sales per restaurants : [5850 6600 7250 7900]
