### Numpy started

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3])
print(arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


### Python list v/s Python array(numpy)

In [ ]:
py_list = [1,2,3]
print(py_list*2)

np_array = np.array([1,2,3])
print(np_array*2)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print(time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print(time.time() - start)

[1, 2, 3, 1, 2, 3]
[2 4 6]
0.06397533416748047
0.0034341812133789062


### Numpy array from scratch

In [ ]:
zeros = np.zeros((2,2))
print(zeros)

ones = np.ones((2,2))
print(ones)

full = np.full((2,2), 7) # give full array of size (2,2) with value 7
print(full)

random = np.random.randint((2,2))
print(random)

sequence = np.arange(0,11,2)
print(sequence)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[1 1]
[ 0  2  4  6  8 10]


### Vector, Matrices, Transpose

In [11]:
vector = np.array([1,2,3])
print(vector)

matrix = np.array([
    [1,2,3], [4,5,6]
    ])
print(matrix)

tensor = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [ ]:
arr = np.array([ [1,2,3], [4,5,6]])

print(f"Shape : {arr.shape}") # rows x columns
print(f"Dimension : {arr.ndim}") # 2D array
print(f"Size : {arr.size}")  # No. of elements
print(f"Data type : {arr.dtype}") # int64 by default

Shape : (2, 3)
Dimension : 2
Size : 6
Data type : int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print(arr)

reshaped = arr.reshape((3,4))
print(reshaped)

# returns copy of a original array
flattened = reshaped.flatten()
print(flattened)

# returns original insted of copy of original array
raveled = reshaped.ravel()
print(raveled)

transpose = reshaped.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
