### Numpy array operations

In [1]:
import numpy as np

### Slicing

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(f"slicing : {arr[1:3]}")
print(f"with step : {arr[1:10:2]}") # last specified 2 is step
print(f"negative index : {arr[-3]}")

slicing : [2 3]
with step : [ 2  4  6  8 10]
negative index : 8


### Access element in 2D array

In [4]:
arr_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])

print(f"specific element : {arr_2d[1,2]}")
print(f"entire row : {arr_2d[1]}")
print(f"entire column : {arr_2d[:, 1]}")

specific element : 6
entire row : [4 5 6]
entire column : [2 5 8]


### Sorting

In [ ]:
unsorted_1d = np.array([1, 7, 4, 2, 5, 3])
print(f"sorted : {np.sort(unsorted_1d)}")

unsorted_2d = np.array([
    [3,1], [1,2], [2,3] 
])
print(f"sorted 2d by column(top to bottom) : {np.sort(unsorted_2d, axis=0)}")  # axis=0 for columns, axis=1 for rows

unsorted_2d = np.array([
    [3,1], [1,2], [2,3]
])
print(f"sorted 2d by rows(left to right) : {np.sort(unsorted_2d, axis=1)}")

sorted : [1 2 3 4 5 7]
sorted 2d by column(top to bottom) : [[1 1]
 [2 2]
 [3 3]]
sorted 2d by rows(left to right) : [[1 3]
 [1 2]
 [2 3]]


### Filter & Filter with mask

In [13]:
nums = np.array([1,2,3,4,5,6])

even = nums[nums % 2 == 0]  # inner expresion is "mask"
print(even)

# making mask manually
mask = nums>3 # store expression
print(f"nums with mask : {nums[mask]}")

[2 4 6]
nums with mask : [4 5 6]


### where() clause

In [14]:
indices = np.where(nums > 3) # similar to mask
print(nums[indices])

[4 5 6]


In [16]:
condition_arr = np.where(nums > 3, "True", "False") # Condition + values (similar to if-else)
print(condition_arr)

['False' 'False' 'False' 'True' 'True' 'True']


### Adding (concatenate) & Deleting  

In [ ]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
print(np.concatenate((arr1,arr2)))

[1 2 3 4]


In [24]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2) # returns new array after deletion
print(deleted)

[1 2 4 5 6]


### Compatibility (Shape of 2 arrays same or not)

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
print(f"complatibility test : {a.shape == b.shape}")

complatibility test : True


### vstack (add rows) & hstack (add columns)

In [23]:
original_arr = np.array([[1,2],[3,4]])
print(f"Original array : {original_arr}")

new_row = np.array([5,6])
print(f"New array after adding row : {np.vstack((original_arr, new_row))}")

new_col = np.array([[5],[6]])
print(f"New array after adding column : {np.hstack((original_arr, new_col))}")

Original array : [[1 2]
 [3 4]]
New array after adding row : [[1 2]
 [3 4]
 [5 6]]
New array after adding column : [[1 2 5]
 [3 4 6]]
